---
# THEME GEM USAGE - visit https://github.com/Shopify/shopify_theme
# Get your api_key and password at your-url.myshopify.com/admin/apps/private

# example code
:api_key: 338497086c61377417447686bd4c81a5
:password: 41d984204fb3d2e43593f4b633539093
:store: storename.myshopify.com
:theme_id:
:ignore_files:
  - settings_data.json
